const COLOR_PRIMARY = "#3BB77E";
const COLOR_PRIMARY_DARK = "#287a54";
const COLOR_PRIMARY_LIGHT = "#DEF9EC";
const COLOR_PRIMARY_BORDER = "#BCE3C9";
const COLOR_TEXT = "#7E7E7E";
const COLOR_TEXT_DARK = "#253D4E";
const COLOR_BORDER = "#ECECEC";
const COLOR_WHITE = "#FFFFFF";
const COLOR_PINK = "#F74B81";
const COLOR_BLUE = "#29A9E1";
const COLOR_ORANGE = "#F2711C";

export default {COLOR_PRIMARY, COLOR_PRIMARY_DARK, COLOR_PRIMARY_LIGHT, COLOR_PRIMARY_BORDER,
    COLOR_TEXT, COLOR_TEXT_DARK, COLOR_BORDER, COLOR_WHITE, COLOR_PINK, COLOR_BLUE, COLOR_ORANGE
};
